[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tsrc/os.ld']
target-dir = "../target"

[target.riscv64gc-unknown-none-elf]
runner = """
    qemu-system-riscv64 
        -serial mon:stdio
        -machine virt
        -drive file=fs.img,format=raw,id=hd0
        -device virtio-blk-device,drive=hd0
        -device virtio-gpu-device
        -kernel
    """