[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tsrc/os.ld']

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -nographic -smp 4 -machine virt -bios none -kernel"
